- name: Install Ollama in Raspberry Pi
  become: true
  block:
    - name: Git checkout Open webui (ollama webui)
      ansible.builtin.git:
        repo: "https://github.com/open-webui/open-webui.git"
        dest: "/home/{{ user }}/open-webui"
        version: "{{ open_webui.git_tag }}"
    - name: Copy docker compose file
      ansible.builtin.template:
        mode: u=rwx,g=rx,o=rx
        src: "{{ playbook_dir }}/roles/ollama/templates/docker-compose.yml.j2"
        dest: "/home/{{ user }}/open-webui/docker-compose.yml"
    - name: Run Docker Compose
      community.docker.docker_compose:
        debug: true
        project_src: "/home/{{ user }}/open-webui"
        files:
          - docker-compose.yml
        state: present
