- name: Install Ollama in Raspberry Pi
  become: true
  block:
    # - name: Update apt packages
    #   ansible.builtin.apt:
    #     update_cache: true
    # - name: Install ollama
    #   ansible.builtin.shell:
    #     cmd: |
    #       set -o pipefail
    #       curl -fsSL https://ollama.com/install.sh | sh
    #   args:
    #     executable: /bin/bash
    #   changed_when: true
    - name: Copy docker compose file
      ansible.builtin.copy:
        mode: u=rwx,g=rx,o=rx
        src: "{{ playbook_dir }}/roles/ollama/files/docker-compose.yml"
        dest: /home/{{ user }}
    - name: Get current directory
      ansible.builtin.command: pwd
      register: current_dir
      changed_when: false
    - name: Print current directory
      ansible.builtin.debug:
        msg: "{{ current_dir.stdout }}"
    - name: Run Docker Compose
      community.docker.docker_compose:
        debug: true
        project_src: "/home/{{ user }}/docker-compose.yml"
        state: present
